ALTER TABLE "marketing_campaigns" ALTER COLUMN "status" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "public"."status";--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('disabled', 'draft', 'failed', 'pending', 'processing', 'success');--> statement-breakpoint
ALTER TABLE "marketing_campaigns" ALTER COLUMN "status" SET DATA TYPE "public"."status" USING "status"::"public"."status";--> statement-breakpoint
ALTER POLICY "templates_select_tenant" ON "templates" TO app_user USING ("templates"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "templates_insert_tenant" ON "templates" TO app_user WITH CHECK ("templates"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "templates_update_tenant" ON "templates" TO app_user USING ("templates"."team_id" = current_setting('app.current_tenant')::uuid) WITH CHECK ("templates"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "templates_delete_tenant" ON "templates" TO app_user USING ("templates"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "whatsapp_business_account_phone_numbers_select_tenant" ON "whatsapp_business_account_phone_numbers" TO app_user USING ("whatsapp_business_account_phone_numbers"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "whatsapp_business_account_phone_numbers_insert_tenant" ON "whatsapp_business_account_phone_numbers" TO app_user WITH CHECK ("whatsapp_business_account_phone_numbers"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "whatsapp_business_account_phone_numbers_update_tenant" ON "whatsapp_business_account_phone_numbers" TO app_user USING ("whatsapp_business_account_phone_numbers"."team_id" = current_setting('app.current_tenant')::uuid) WITH CHECK ("whatsapp_business_account_phone_numbers"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "whatsapp_business_account_phone_numbers_delete_tenant" ON "whatsapp_business_account_phone_numbers" TO app_user USING ("whatsapp_business_account_phone_numbers"."team_id" = current_setting('app.current_tenant')::uuid);