ALTER POLICY "contacts_select_tenant" ON "contacts" TO app_user USING ("contacts"."team_id" = current_setting('app.current_tenant')::uuid AND "contacts"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "contacts_insert_tenant" ON "contacts" TO app_user WITH CHECK ("contacts"."team_id" = current_setting('app.current_tenant')::uuid AND "contacts"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "contacts_update_tenant" ON "contacts" TO app_user USING ("contacts"."team_id" = current_setting('app.current_tenant')::uuid AND "contacts"."deleted_at" IS NULL) WITH CHECK ("contacts"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "conversations_select_tenant" ON "conversations" TO app_user USING ("conversations"."team_id" = current_setting('app.current_tenant')::uuid AND "conversations"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "conversations_insert_tenant" ON "conversations" TO app_user WITH CHECK ("conversations"."team_id" = current_setting('app.current_tenant')::uuid AND "conversations"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "conversations_update_tenant" ON "conversations" TO app_user USING ("conversations"."team_id" = current_setting('app.current_tenant')::uuid AND "conversations"."deleted_at" IS NULL) WITH CHECK ("conversations"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "leads_select_tenant" ON "leads" TO app_user USING ("leads"."team_id" = current_setting('app.current_tenant')::uuid AND "leads"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "leads_insert_tenant" ON "leads" TO app_user WITH CHECK ("leads"."team_id" = current_setting('app.current_tenant')::uuid AND "leads"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "leads_update_tenant" ON "leads" TO app_user USING ("leads"."team_id" = current_setting('app.current_tenant')::uuid AND "leads"."deleted_at" IS NULL) WITH CHECK ("leads"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "list_views_select_tenant" ON "list_views" TO app_user USING ("list_views"."team_id" = current_setting('app.current_tenant')::uuid AND "list_views"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "list_views_insert_tenant" ON "list_views" TO app_user WITH CHECK ("list_views"."team_id" = current_setting('app.current_tenant')::uuid AND "list_views"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "list_views_update_tenant" ON "list_views" TO app_user USING ("list_views"."team_id" = current_setting('app.current_tenant')::uuid AND "list_views"."deleted_at" IS NULL) WITH CHECK ("list_views"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "marketing_campaigns_select_tenant" ON "marketing_campaigns" TO app_user USING ("marketing_campaigns"."team_id" = current_setting('app.current_tenant')::uuid AND "marketing_campaigns"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "marketing_campaigns_insert_tenant" ON "marketing_campaigns" TO app_user WITH CHECK ("marketing_campaigns"."team_id" = current_setting('app.current_tenant')::uuid AND "marketing_campaigns"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "marketing_campaigns_update_tenant" ON "marketing_campaigns" TO app_user USING ("marketing_campaigns"."team_id" = current_setting('app.current_tenant')::uuid AND "marketing_campaigns"."deleted_at" IS NULL) WITH CHECK ("marketing_campaigns"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "tags_select_tenant" ON "tags" TO app_user USING ("tags"."team_id" = current_setting('app.current_tenant')::uuid AND "tags"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "tags_insert_tenant" ON "tags" TO app_user WITH CHECK ("tags"."team_id" = current_setting('app.current_tenant')::uuid AND "tags"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "tags_update_tenant" ON "tags" TO app_user USING ("tags"."team_id" = current_setting('app.current_tenant')::uuid AND "tags"."deleted_at" IS NULL) WITH CHECK ("tags"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "team_member_limits_select_tenant" ON "team_member_limits" TO app_user USING ("team_member_limits"."team_id" = current_setting('app.current_tenant')::uuid AND "team_member_limits"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "team_member_limits_insert_tenant" ON "team_member_limits" TO app_user WITH CHECK ("team_member_limits"."team_id" = current_setting('app.current_tenant')::uuid AND "team_member_limits"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "team_member_limits_update_tenant" ON "team_member_limits" TO app_user USING ("team_member_limits"."team_id" = current_setting('app.current_tenant')::uuid AND "team_member_limits"."deleted_at" IS NULL) WITH CHECK ("team_member_limits"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "team_members_usage_tracking_select_tenant" ON "team_members_usage_tracking" TO app_user USING ("team_members_usage_tracking"."team_id" = current_setting('app.current_tenant')::uuid AND "team_members_usage_tracking"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "team_members_usage_tracking_insert_tenant" ON "team_members_usage_tracking" TO app_user WITH CHECK ("team_members_usage_tracking"."team_id" = current_setting('app.current_tenant')::uuid AND "team_members_usage_tracking"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "team_members_usage_tracking_update_tenant" ON "team_members_usage_tracking" TO app_user USING ("team_members_usage_tracking"."team_id" = current_setting('app.current_tenant')::uuid AND "team_members_usage_tracking"."deleted_at" IS NULL) WITH CHECK ("team_members_usage_tracking"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "templates_select_tenant" ON "templates" TO app_user USING ("templates"."team_id" = current_setting('app.current_tenant')::uuid AND "templates"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "templates_insert_tenant" ON "templates" TO app_user WITH CHECK ("templates"."team_id" = current_setting('app.current_tenant')::uuid AND "templates"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "templates_update_tenant" ON "templates" TO app_user USING ("templates"."team_id" = current_setting('app.current_tenant')::uuid AND "templates"."deleted_at" IS NULL) WITH CHECK ("templates"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "whatsapp_business_account_phone_numbers_select_tenant" ON "whatsapp_business_account_phone_numbers" TO app_user USING ("whatsapp_business_account_phone_numbers"."team_id" = current_setting('app.current_tenant')::uuid AND "whatsapp_business_account_phone_numbers"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "whatsapp_business_account_phone_numbers_insert_tenant" ON "whatsapp_business_account_phone_numbers" TO app_user WITH CHECK ("whatsapp_business_account_phone_numbers"."team_id" = current_setting('app.current_tenant')::uuid AND "whatsapp_business_account_phone_numbers"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "whatsapp_business_account_phone_numbers_update_tenant" ON "whatsapp_business_account_phone_numbers" TO app_user USING ("whatsapp_business_account_phone_numbers"."team_id" = current_setting('app.current_tenant')::uuid AND "whatsapp_business_account_phone_numbers"."deleted_at" IS NULL) WITH CHECK ("whatsapp_business_account_phone_numbers"."team_id" = current_setting('app.current_tenant')::uuid);--> statement-breakpoint
ALTER POLICY "whatsapp_business_accounts_select_tenant" ON "whatsapp_business_accounts" TO app_user USING ("whatsapp_business_accounts"."team_id" = current_setting('app.current_tenant')::uuid AND "whatsapp_business_accounts"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "whatsapp_business_accounts_insert_tenant" ON "whatsapp_business_accounts" TO app_user WITH CHECK ("whatsapp_business_accounts"."team_id" = current_setting('app.current_tenant')::uuid AND "whatsapp_business_accounts"."deleted_at" IS NULL);--> statement-breakpoint
ALTER POLICY "whatsapp_business_accounts_update_tenant" ON "whatsapp_business_accounts" TO app_user USING ("whatsapp_business_accounts"."team_id" = current_setting('app.current_tenant')::uuid AND "whatsapp_business_accounts"."deleted_at" IS NULL) WITH CHECK ("whatsapp_business_accounts"."team_id" = current_setting('app.current_tenant')::uuid);