export const RESPONSE_CODE = {
  BAD_REQUEST: 400,
  CONFLICT: 409,
  CREATED: 201,

  FORBIDDEN: 403,
  INTERNAL_ERROR: 500,
  NO_CONTENT: 204,
  NOT_FOUND: 404,
  SERVICE_UNAVAILABLE: 503,

  SUCCESS: 200,
  UNAUTHORIZED: 401,
} as const;

export type ResponseCode = (typeof RESPONSE_CODE)[keyof typeof RESPONSE_CODE];
